-- Create the leaderboard table
create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null,
  timestamp timestamptz not null default now()
);

-- Create the employees table
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null
);

-- Create function to create leaderboard table
create or replace function create_leaderboard_table()
returns void
language plpgsql
as $$
begin
  create table if not exists public.leaderboard (
    id bigint generated by default as identity primary key,
    player_name text not null,
    score integer not null,
    timestamp timestamptz not null default now()
  );
end;
$$;

-- Create function to create employees table
create or replace function create_employees_table()
returns void
language plpgsql
as $$
begin
  create table if not exists public.employees (
    id bigint generated by default as identity primary key,
    name text not null,
    image_url text not null
  );
end;
$$;